### ISSUE TITLE
BGG++ doesn't work on "new" BGG pages

### ISSUE THREAD

**Issue by bivaterl** [scraimer/bggplusplus#4]
This is a fantastic tool and I love using it, but it disappears when it's on one of the "new" layout pages for BGG (IE new game pages or new images pages). Is it possible for it to stay persistent on those pages? For example, if I have an image uploaded by a user in my subscriptions and I use the tool to jump from new item to new item (which it does just fine on the older, geeklist style pages), but then it jumps me to an image page in the new format, the icon in the top indicating BGG++ is working disappears. I have to go back to my subscriptions list and pick a new item that isn't displayed on the "new" BGG style/theme for BGG++ to work.

**Comment by scraimer** [comment]
Sorry for the late reply - I never got an email about this issue in GitHub (which I had assumed would happen) sorry. I've fixed this partially in v0.0.11 (which you should have already) but there was a bug, which was fixed by @rafal-watorski and I've just published into v0.0.12, which you should get in a couple of days.
